export const LIST_ALL_TEAM_MEMBERS = "LIST_ALL_TEAM_MEMBERS";

export const LIST_ALL_SAMPLE_MEMBERS = "LIST_ALL_SAMPLE_MEMBERS";

export const ADD_TASK = "ADD_TASK";

export const ADD_ITEM = "ADD_ITEM";

export const SET_VISIBLE_FILTER = "SET_VISIBLE_FILTER";

export const CHANGE_THEME = "CHANGE_THEME";

export const CHANGE_ITEM_CONTENT = "CHANGE_ITEM_CONTENT";

export const DELETE_ITEM = "DELETE_ITEM";

export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";

export const CREATE_NEW_TEAM = "CREATE_NEW_TEAM";

export const DELETE_TEAM_BY_ID = "DELETE_TEAM_BY_ID";

export const CHANGE_NAME_BY_ID = "CHANGE_NAME_BY_ID";

export const SEARCH_ANYTHING = "SEARCH_ANYTHING";

export const UPDATE_LIST = "UPDATE_LIST";

export const CURRENT_ROW = "CURRENT_ROW";

export const ADD_NEW_ROW = "ADD_NEW_ROW";

export const DELETE_ROW = "DELETE_ROW";

export const SAVE_ROW = "SAVE_ROW";

//colors
export const GENERATE_COLOR_REQUEST = 'GENERATE_COLOR_REQUEST';

export const GENERATE_COLOR_SUCCESS = 'GENERATE_COLOR_SUCCESS';

export const CHANGE_COLOR = 'CHANGE_COLOR';

export const COPY_COLOR_TO_CLIPBOARD = 'COPY_COLOR_TO_CLIPBOARD';

//gradients
export const GENERATE_GRADIENT_REQUEST = 'GENERATE_GRADIENT_REQUEST';

export const GENERATE_GRADIENT_SUCCESS = 'GENERATE_GRADIENT_SUCCESS';

export const CHANGE_GRADIENT = 'CHANGE_GRADIENT';

export const COPY_GRADIENT_TO_CLIPBOARD = 'COPY_GRADIENT_TO_CLIPBOARD';

export const ADD_NEW_COLOR = 'ADD_NEW_COLOR';
export const EDIT_ANGLE = 'EDIT_ANGLE';
export const CHANGE_GRADIENT_DIRECTION = 'CHANGE_GRADIENT_DIRECTION';
export const TOGGLE_EDIT_COLOR_OF_GRADIENT = 'TOGGLE_EDIT_COLOR_OF_GRADIENT';
export const EDIT_COLOR_OF_GRADIENT = 'EDIT_COLOR_OF_GRADIENT';
export const TOGGLE_SLIDER = 'TOGGLE_SLIDER';
export const START_UPDATE_COLOR_STOP = 'START_UPDATE_COLOR_STOP';
export const UPDATE_COLOR_STOP = 'UPDATE_COLOR_STOP';
export const DELETE_SELECTED_COLOR = 'DELETE_SELECTED_COLOR';

//settings
export const TOGGLE_PREFIX = 'TOGGLE_PREFIXES';
export const TOGGLE_FALLBACK = 'TOGGLE_FALLBACK';
